tools:
  - formula: fzf
    bin: fzf
  - formula: lazygit
    bin: lazygit
  - formula: neovim
    bin: nvim
  - formula: ripgrep
    bin: rg
  - formula: git-delta
    bin: delta
  - formula: htop
    bin: htop
